### ISSUE TITLE
Remove from the abstract

### ISSUE THREAD

**Issue by PoorPeer** [DemocracyEarth/paper#174]
Good Work - I am impressed! I suggest you to remove some technical details from the abstract to make it more easy readable. I suggest this part to be removed: 
"Our proposal introduces cryptographically induced equality: as long as any person is able to validate his or her self-sovereign identity, they will receive a corresponding share of votes that is equal to the share of every active participant in the network. We define a Proof of Identity process that avoids central authority by introducing the concept of attention mining which incentivizes participants to strengthen the trust of votes by performing simple tests aimed at detecting replicants. Finally votes get dripped to valid participants under a Universal Basic Income mechanism with a goal of finding a proper equilibrium in the historical tension between money and politics."

**Comment by santisiri** [comment]
Thanks for the observation. I included that once we finished the paper because after all the abstract does serve the purpose to provide a synthesis of all the topics that get covered by the paper. For those unfamiliar with crypto literature might come as a bit odd, but also for those who are used to this kind of stuff I think it's indispensable.

**Comment by paulamlb** [comment]
I will work on a glossary to explain all those terms and add it to the FAQ file..

**Comment by PoorPeer** [comment]
Resolved!

**Comment by santisiri** [comment]
@paulamlb great idea paula!
