### ISSUE TITLE
Money as votes vs. votes as money....

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/paper#30]
re: modes of interacting with Votes: "Anonymous: Corporations and private institutions (often referred as Anonymous Societies in many jurisdictions) can benefit by having a voting token secured over a blockchain that can easily interoperate with other crypto assets and without the requirement of having an approved member signature attached to the transaction. Anonymous entities holding legitimate VOTEs can interact with a collective as long as the VOTEs have been granted by the collective's constitution."

Is this saying that VOTES when enacted by individuals with organizations, are currency? is this essentially how we are creating/defining the basis of VOTE's economic value?  (so that requires people to accept they are 'buying votes' is the same as carrying around a dollar bill and spending it, or putting a thumbs up on a story). Is there an upward limit on the number of VOTES that can be bought/awarded? 

 If time is money, and if votes are money (currency), then time and votes are equivalent, a kind of full circle way of understanding where power resides/is leveraged.

**Comment by paulamlb** [comment]
If VOTEs are being dripped over time to all identified members of the network, then in addition to being a tradable token (coin) it's also a granted right. IMHO setting a cap on how many votes you can sell could be a great way to protect this right while strenghtening value stability over time. 

I also think that, being this, to my knowledge, an unprecedented kind of initial offering, it is important to address in a very clear manner those implementation settings, so it will help people understand what is the nature of the token being launched. I imagine that the right versus coin question will be on everyones mind, so it's good to get that straight. The UBI, sell cap, and all other implementation settings, in that sense, could be key to make things clear. 

The UBI section is still very raw but it depends on those important decisions in order to move forward.

**Comment by SFSandra** [comment]
@herbstephens what do you think
