### ISSUE TITLE
"Collective" synonymous to "Organization"?

### ISSUE THREAD

**Issue by herbstephens** [DemocracyEarth/paper#31]
Want to make sure we are clear on this ... mainly because most (at least in the U.S.) will not equate "collective" with a nation-state or large organization. 

If we use term "collective"...must make sure it is equated to "organization" clearly.

**Comment by santisiri** [comment]
I'm using 'collective' since it's the way I refer to this in the codebase of Sovereign. But if it makes more sense to name this as 'Organization' happy to do it. I am in fact aware of the connotation that collective might have and it could be wise to change this. You think its better to go with 'Organization'?

**Comment by dwightmwilson** [comment]
i'd vote for organization and agree about challenge of the word 'collective'

**Comment by santisiri** [comment]
great to see you here dwight! way to go. will change to 'organization'.
